export const FETCH_EPISODES_PENDING = 'FETCH_EPISODES_PENDING';
export const FETCH_EPISODES_SUCCESS = 'FETCH_EPISODES_SUCCESS';
export const FETCH_EPISODES_ERROR = 'FETCH_EPISODES_ERROR';

export const FILTER_LATEST_EPISODE = 'FILTER_LATEST_EPISODE';